[package]
name = "nasci4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
threadpool = "1.8.1"
bit_reverse = "0.1.8"
sha256 = "1.0.0"
rand = "0.8.5"
